// Common juniper (Juniperus communis) — irregular prostrate/upright mountain
// scrub with needle-spray cards and sparse glaucous berry cones.
export const commonJuniper = {
  name: 'Common Juniper',
  latin: 'Juniperus communis',
  category: 'shrub',
  bark: 'common_juniper_branch_albedo.png',
  leaf: 'juniper_scrub_albedo.png',
  biome: 'temperate',
  tileWorldSize: 0.4,
  plantSink: 0.015,
  foliageType: 'sprayClusters',
  fruit: {
    mesh: 'juniper_berry.glb',
    perBranch: 2,
    chance: 1,
    startFrac: 0.12,
    maxCount: 20,
  },
  foliage: {
    clustersPerBranch: 5,
    clusterSize: 0.34,
    clusterSizeVar: 0.32,
    clusterQuads: 2,
    alphaTest: 0.48,
    tint: 0xc4d4b6,
    transmit: [0.18, 0.28, 0.16],
    downAngle: 24,
    downAngleV: 18,
    droop: 8,
    startFrac: 0.12,
    parentSprays: 0.7,
    rotate: 137,
  },
  params: {
    trunks: 6,
    trunkSplayDeg: 42,
    firstForkHeight: 0.09,
    armLength: 0.33,
    armFalloff: 0.86,
    forkGenerations: 4,
    branchiness: 0.86,
    forkSpread: 25,
    forkTriChance: 0.12,
    curlUp: 0.24,
    armBend: 10,
    gnarliness: 16,
    continuationKink: 12,
    forkRadiusKeep: 0.8,
    trunkRadius: 0.012,
    trunkFlare: 1.2,
    branchRepel: 0.66,
    minRadius: 0.0025,
    radialSegs: 6,
    segCurveRes: 3,
    tileWorldSize: 0.4,
    barkGrainU: true,
    windWeightScale: 0.18,
  },
};
