// European red raspberry (Rubus idaeus) — arching multi-cane temperate shrub
// with compound-leaf sprays and real drupelet fruit clusters.
export const raspberry = {
  name: 'European Red Raspberry',
  latin: 'Rubus idaeus',
  category: 'shrub',
  bark: 'raspberry_cane_albedo.png',
  leaf: 'raspberry_spray_albedo.png',
  biome: 'temperate',
  tileWorldSize: 0.35,
  plantSink: 0.012,
  foliageType: 'sprayClusters',
  fruit: {
    mesh: 'raspberry_cluster.glb',
    perBranch: 2,
    chance: 1,
    startFrac: 0.12,
    maxCount: 10,
  },
  foliage: {
    clustersPerBranch: 4,
    clusterSize: 0.24,
    clusterSizeVar: 0.24,
    clusterQuads: 2,
    alphaTest: 0.38,
    tint: 0xffffff,
    transmit: [0.34, 0.5, 0.2],
    downAngle: 38,
    downAngleV: 16,
    droop: 18,
    startFrac: 0.12,
    parentSprays: 1,
    rotate: 137,
  },
  params: {
    trunks: 6,
    trunkSplayDeg: 32,
    firstForkHeight: 0.08,
    armLength: 0.27,
    armFalloff: 0.88,
    forkGenerations: 4,
    branchiness: 0.66,
    forkSpread: 21,
    forkTriChance: 0.04,
    curlUp: 0.18,
    armBend: 16,
    gnarliness: 9,
    continuationKink: 8,
    forkRadiusKeep: 0.72,
    trunkRadius: 0.011,
    trunkFlare: 1.12,
    branchRepel: 0.62,
    minRadius: 0.0022,
    radialSegs: 6,
    segCurveRes: 4,
    tileWorldSize: 0.35,
    barkGrainU: true,
    windWeightScale: 0.28,
  },
};
